Code for basic UI
herokudev/Math-Magicians pull request #2
Opened 2021-09-21 22:53 UTC by herokudev

Delete all the boilerplate from CRA (text, images, styles).
Develop just the UI of the calculator; the math logic to make it work will be added in the next project.

2021-09-21 23:24 UTC, addod19 requested changes
### Hi @herokudev, 

Good job so far! Git-flow followed :100: Right linter files used :+1: Awesome first attempt :1st_place_medal: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Writing more commit messages to track our progress. This helps us track and manage bugs if presents

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-21 23:24 UTC, addod19 commented on src/components/Calculator.js
> +/* eslint-disable react/prefer-stateless-function */
- [ ] It would be better if we fix the linters errors instead of disabling them. Fixing it helps us write clean and better code

2021-09-21 23:24 UTC, addod19 commented on src/App.css
> +#root {
- [ ] It would be better if we delete more of the boilerplate code of the CRA, here are a few hints:
  - [ ] The logo.SVG, index.css, logo192.png, logo512.png, manifest.json file. Also, let us remember to remove its links in the files referenced

2021-09-21 23:24 UTC, addod19 commented on src/App.css
> +  align-items: center;
- [ ] It would be better if we apply the CSS DRY principle, the following properties have been repeated. Let us kindly fix them. Applying the DRY principle makes our codebase easier to maintain
```
  display: flex;
  justify-content: center;
  align-items: center;
```

2021-09-21 23:24 UTC, addod19 commented on src/App.css
> +.util,
- [ ] It would be better to specify how non-developers like hiring managers can use the application. For example; `git clone https://github.com/herokudev/Math-Magicians.git`, next we install dependencies `npm i`, then we start the app with `npm start`. That's it!!!!

2021-09-22 00:15 UTC, herokudev commented on src/App.css
> +.util,
Instructions on the ReadME file.

2021-09-22 00:15 UTC, herokudev commented on src/App.css
> +#root {
Files deleted.

2021-09-22 00:16 UTC, herokudev commented on src/components/Calculator.js
> +/* eslint-disable react/prefer-stateless-function */
Have no linter errors.

2021-09-22 01:04 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @herokudev, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 14:54 UTC, merged